apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular17-app
    tier: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: '3000'
      port: 3000
      targetPort: 3000
  selector:
    app: angular17-app
    tier: backend
