apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular17-app
    tier: backend
  name: backend
spec:
  type: NodePort
  selector:
    app: angular17-app
    tier: backend
  ports:
    - name: backend-port
      port: 3000 # internally used port
      nodePort: 30951 # will be exposed in the cluster, external traffic can be routed to it
