apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: angular17-app
  ports:
    - name: http
      port: 8080 # internally used port
      nodePort: 30950 # will be exposed in the cluster, external traffic can be routed to it
      protocol: TCP
