apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  # exposes port 80 statically
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: angular17-app
    tier: frontend
