apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular17-app
      tier: frontend
  template:
    metadata:
      labels:
        app: angular17-app
        tier: frontend
    spec:
      containers:
        - name: client
          image: angular17-browser
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_HOST
              value: http://localhost:3000
