kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - hostPort: 8080 # kind will expose this port to localhost
      containerPort: 30950 # all traffic will be routed to this port, it needs to match the nodePort of the frontend service -->
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp, udp is also possible
  labels:
    tier: frontend # nodeSelector constraint to services with this label
- role: worker
  extraPortMappings:
    - hostPort: 3000 # kind will expose this port to localhost
      containerPort: 30951 # all traffic will be routed to this port, it needs to match the nodePort of the backend service
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp, udp is also possible
  labels:
    tier: backend # nodeSelector constraint to services with this label
